CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) not null unique,
    password VARCHAR(255) not null
);

CREATE TABLE to_do_task (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    due_date DATE,
    creation_date DATE,
    check_mark BOOLEAN,
    completion_date DATE,
    user_id BIGINT,

    CONSTRAINT FK_task_user_id FOREIGN KEY(user_id) REFERENCES users (id)
);