name: task-tool
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: eu-north-1  # Set the AWS region here
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t 512269564608.dkr.ecr.eu-north-1.amazonaws.com/todo-task:${IMAGE_TAG} .
          docker push 512269564608.dkr.ecr.eu-north-1.amazonaws.com/todo-task:${IMAGE_TAG}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1  # Add this line to specify the AWS region

      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-tool.json
          container-name: task-tool
          image: 512269564608.dkr.ecr.eu-north-1.amazonaws.com/todo-task:${{ steps.build-image.outputs.image }}
        env:
          AWS_REGION: eu-north-1  # Set the AWS region here

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: task-tool-service-v3
          cluster: task-tool
          wait-for-service-stability: true
        env:
          AWS_REGION: eu-north-1  # Set the AWS region here