name: task-tool
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t 512269564608.dkr.ecr.eu-north-1.amazonaws.com/todo-task:${IMAGE_TAG} .
          docker push 512269564608.dkr.ecr.eu-north-1.amazonaws.com/todo-task:${IMAGE_TAG}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-tool.json
          container-name: task-tool
          image: 512269564608.dkr.ecr.eu-north-1.amazonaws.com/todo-task:${{ steps.build-image.outputs.image }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: your-service-name
          cluster: your-cluster-name
          wait-for-service-stability: true
